home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # /home/
    url(r'^$', views.index, name='index'),
]

search/urls.py
from django.conf.urls import url
from . import views

#This is a namespace
app_name = 'search'

urlpatterns = [
    #This is the homepage of the search app
    #/search/      ~this is what index will be referencing
    url(r'^$', views.index, name='index'),



    # /Search/<Album id>/    ~this is what detail will be referencing
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),

    # /Search/<Album id>/add_to_cart    ~this is what detail will be referencing
    url(r'^(?P<book_id>[0-9]+)/add_to_cart/$', views.add_to_cart, name='add_to_cart'),

    # /search/cart ~shows the contents of the cart
    url(r'^cart/$', views.cart_detail, name='cart_detail'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('search.urls')),
    url(r'^home/', include('home.urls'))
]

cart/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models


class Book(models.Model):
    cover = models.CharField(max_length=10000, null=True)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    publisher = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100)
    description = models.CharField(max_length=999999)
    new_book_quantity = models.FloatField()
    used_book_quantity = models.FloatField()
    rental_book_quantity = models.FloatField()
    ebook_quantity = models.FloatField()
    new_book_price = models.FloatField()
    used_book_price = models.FloatField()
    rental_book_price = models.FloatField()
    ebook_price = models.FloatField()
    in_cart = models.BooleanField(default=False)

    def __str__(self):
            return self.title + ' - ' + self.author


class Course(models.Model):
    # inside of the ForeignKey function it should be (book, on_delete=models.CASCADE)
    book = models.ForeignKey(Book)
    course_number = models.CharField(max_length=100)
    course_name = models.CharField(max_length=100)
    profesor = models.CharField(max_length=100)
    semester = models.CharField(max_length=100)
    section = models.IntegerField()

    def __str__(self):
            return self.course_name + ' - ' + self.profesor

home/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

cart/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm


def index(request):
    return render(request, "home/index.html")


class UserFormView(View):
    form_class = UserForm

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('/home')

search/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, Course

cart = []


def index(request):
    # used to connect to the database
    all_books = Book.objects.all()
    return render(request, 'search/index.html', {'all_books': all_books})


def detail(request, book_id):
    # book = Book.objects.get(pk = book_id)
    book = get_object_or_404(Book, id=book_id)
    return render(request, 'search/detail.html', {'book': book})


def add_to_cart(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    try:
        selected_book = book
    except(KeyError, Book.DoesNotExist):
        return render(request, 'search/detail.html', {
            'book': book,
            'error_message': "You did not select a valid book"
        })
    else:
        cart.append(selected_book)
        # selected_book.in_cart = True
        # selected_book.save()
        return render(request, 'search/detail.html', {'book': book})


def cart_detail(request):
    book_ids = []
    for book in cart:
        book_ids.append(book.id)
    books_in_cart = Book.objects.filter(pk__in=book_ids)
    return render(request, 'search/cart.html', {'books_in_cart': books_in_cart})

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<nav class="nav navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/home">Home</a>
            <a class="navbar-brand" href="/search">Search</a>
            <a class="navbar-brand" href="/search">About Us</a>
            <a class="navbar-brand" href="/admin">Log In</a>
        </div>
    </div>
</nav>

<body>

</body>
</html>

search/templates/search/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

search/templates/search/cart.html
{% for book in books_in_cart %}
    <div>{{ book.title }}</div>
{% endfor %}

search/templates/search/detail.html
<img src="{{ book.cover }}">

<h1>{{ book.title }}</h1>
<h2>{{ book.author }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'search:add_to_cart' book.id %}" method="post">
    {% csrf_token %}
    {% for book in book.course_set.all %}
        <input type="radio" id="book{{ forloop.counter }}" name="book" value="{{ book.id }}" />
        <label for="book{{ forloop.counter }}">
            {{ book.title }}
            {% if book.in_cart %}
                <img src="http://img.waveprice.com/user/2015/09/15/118/StR1gkEKBl.100.jpg" />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Add">
</form>

search/templates/search/index.html
{%  load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'search/style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!this is the logo>
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'search:index' %}">Home</a>
            <a class="navbar-brand" href="{% url 'search:index' %}">search</a>
            <a class="navbar-brand" href="{% url 'search:index' %}">About Us</a>
            <a class="navbar-brand" href="{% url 'search:index' %}">Log In</a>

        </div>
    </div>
</nav>

{% if all_books %}
    <h3>Here is a full list of Books</h3>
    <ul>
        {% for book in all_books %}
        <li><a href="{% url 'search:detail' book.id %}"> {{ book.title }}</a> </li>
        {%  endfor %}
    </ul>
{% else %}
    <h3>You Search produced no results</h3>
{% endif %}